//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSA_Net_Client.Providers.Tractis {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RequestTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RequestTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TSA_Net_Client.Providers.Tractis.RequestTemplates", typeof(RequestTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SignRequest xmlns=&quot;urn:oasis:names:tc:dss:1.0:core:schema&quot;&gt;
        ///  &lt;OptionalInputs&gt;
        ///	&lt;ReturnSigningTimeInfo/&gt;
        ///    &lt;SignatureType&gt;urn:oasis:names:tc:dss:1.0:core:schema:XMLTimeStampToken&lt;/SignatureType&gt;
        ///  &lt;/OptionalInputs&gt;
        ///  &lt;InputDocuments&gt;
        ///    &lt;Document&gt;
        ///      &lt;Base64Data&gt;{0}&lt;/Base64Data&gt;
        ///    &lt;/Document&gt;
        ///  &lt;/InputDocuments&gt;
        ///&lt;/SignRequest&gt;.
        /// </summary>
        internal static string StampRequest {
            get {
                return ResourceManager.GetString("StampRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;dss:VerifyRequest xmlns:dss=&quot;urn:oasis:names:tc:dss:1.0:core:schema&quot; Profile=&quot;urn:oasis:names:tc:dss:1.0:profiles:XAdES&quot;&gt;
        ///  &lt;dss:InputDocuments&gt;
        ///    &lt;dss:DocumentHash ID=&quot;Doc1&quot;&gt;
        ///      &lt;ds:DigestMethod Algorithm=&quot;http://www.w3.org/2000/09/xmldsig#sha1&quot; xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot;/&gt;
        ///      &lt;ds:DigestValue xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot;&gt;{0}&lt;/ds:DigestValue&gt;
        ///    &lt;/dss:DocumentHash&gt;
        ///  &lt;/dss:InputDocuments&gt;
        ///  &lt;dss:SignatureObject&gt;{1}&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VerifyRequest {
            get {
                return ResourceManager.GetString("VerifyRequest", resourceCulture);
            }
        }
    }
}
